package game.actions;

import edu.monash.fit2099.engine.actions.Action;
import edu.monash.fit2099.engine.actors.Actor;
import edu.monash.fit2099.engine.positions.GameMap;

import java.util.Random;

/**
 * An action that represents a Creature attacking a Targetable actor.
 * The attack has a fixed chance to hit, which deals a set amount of damage on success.
 * This action is generated by AttackBehaviour and executed by hostile creatures.
 */
public class AttackAction extends Action {
    private static final int HIT_CHANCE = 10;
    private final Actor target;
    private final Random random = new Random();

    /**
     * Constructor for AttackAction
     *
     * @param target the actor to be attacked
     */
    public AttackAction(Actor target) {
        this.target = target;
    }

    /**
     * Executes the attack against the target. Has a 10% chance to succeed and hit.
     * Deals 1 damage on success.
     *
     * @param actor The actor performing the action.
     * @param map The map the actor is on.
     * @return a String describing the outcome of the attempted attack
     */
    @Override
    public String execute(Actor actor, GameMap map) {
        if (random.nextInt(100) < HIT_CHANCE) {
            target.hurt(1);
            return actor + " attacks " + target + " for 1 damage.";
        }
        return actor + " misses " + target + ".";
    }

    /**
     * Descriptor for the menu console,
     * to inform players on what the action entails.
     *
     * @param actor The actor performing the action
     * @return a String confirming the action taken
     */
    @Override
    public String menuDescription(Actor actor) {
        return actor + " attacks " + target;
    }
}